### ISSUE TITLE
Web API errors are not handled

### ISSUE THREAD

**Issue by sefischer** [semproj-tierversuche/web-frontend#5]
There is no error message when the API returns a non-200 HTTP status code, or doesn't answer at all.

### Variant 1
1. Visit search page
2. Enter a PMID that is not in our database, for example `29224783`
3. Click Search button
### Variant 2
1. Visit search page
2. Enter a PMID that is in the database, but has no associated results, for example `16120778`
3. Click Search button
4. Click Continue button

### Variant 1
Nothing happens, although the API has returned a 404 error.
### Variant 2
The results page appears with a loading indicator superimposed. The loading indicator never goes away, although the API has returned a 404 error.

## Expected Result
An error message is shown, indicating that (a) the PMID has not been found (in the case of a 404 API status code) or (b) an API error occured (for any other status code)

**Comment by Alpayyil** [comment]
Variante 2 kann ich nicht reproduzieren

**Comment by sefischer** [comment]
Da war vmtl. gerade die Datenbank leer, jetzt sollte es wieder auftreten. Ansonsten kannst du auch für den gleichen Effekt diesen Link anklicken: http://141.20.31.92/frontend/result/16120778
